---
- name: install samba
  apt:
    name: "{{ item }}"
    state: "{{ samba_pkg_install_latest | default('no') | ternary('latest', 'present') }}"
    update_cache: yes
  with_items: "{{ samba_pkgs }}"
  tags:
    - samba
    - pkg
    - apt
