---
- name: get stat of smb.conf
  stat:
    follow: "{{ samba_config_follow | default(omit) }}"
    get_checksum: "{{ samba_config_get_checksum | default(omit) }}"
    get_md5: "{{ samba_config_get_md5 | default(omit)  }}"
    path: "{{ samba_config_dest }}"
  register: samba_config_st
  tags:
    - samba
    - config

- name: get stat of default smb.conf
  stat:
    follow: "{{ samba_config_follow | default(omit) }}"
    get_checksum: "{{ samba_config_get_checksum | default(omit) }}"
    get_md5: "{{ samba_config_get_md5 | default(omit)  }}"
    path: "{{ samba_config_dest }}.default"
  register: samba_config_st_default
  tags:
    - samba
    - config

- name: move default smb.conf into place
  command: "cp {{ samba_config_dest }}.default {{ samba_config_dest }} creates={{ samba_config_dest }}"
  when: >
    (not samba_config_st.stat.exists) and samba_config_st_default.stat.exists
  tags:
    - samba
    - config

