---
# tasks file for samba
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_pkg_mgr }}.yml"
  tags:
    - always

# Install packages
- include: pacman.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - samba
    - pacman

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
    - samba
    - pkg
    - pacman

# Move default smb.conf into place, if needed.  Also get initial checksum for
# later comparison when handlers fire.
- include: config.yml
  tags:
    - samba
    - config

# Restart samba services
- include: service.yml
  tags:
    - samba
    - service
