---
# tasks file for samba

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_pkg_mgr }}.yml"
  tags:
    - always

# Install packages
- include: pacman.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - samba
    - pacman

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
    - samba
    - pkg
    - apt

- include: yum.yml
  when: ansible_pkg_mgr == 'yum'
  tags:
    - samba
    - pkg
    - yum

# Move default smb.conf into place, if needed.  Also get initial checksum for
# later comparison when handlers fire.
- include: config.yml
  tags:
    - samba
    - config

- name: get pre-run stat of smb.conf
  stat:
    follow: "{{ samba_config_follow | default(omit) }}"
    get_checksum: "{{ samba_config_get_checksum | default(omit) }}"
    get_md5: "{{ samba_config_get_md5 | default(omit)  }}"
    path: "{{ samba_config_dest }}"
  register: samba_config_st_pre
  when: samba_services_restarted_on_change | bool
  changed_when: samba_services_restarted_on_change | bool
  notify: get post-run stat of smb.conf
  tags:
    - samba
    - config
    - service

# Restart samba services
- include: service.yml
  tags:
    - samba
    - service

- name: notify samba services restart handler
  debug: notify samba services restart handler
  when: samba_services_restarted | bool
  changed_when: samba_services_restarted | bool
  notify: restart samba services
