---
- name: get pre-run stat of smb.conf
  stat:
    follow: "{{ samba_config_follow | default(omit) }}"
    get_checksum: "{{ samba_config_get_checksum | default(omit) }}"
    get_md5: "{{ samba_config_get_md5 | default(omit)  }}"
    path: "{{ samba_config_dest }}"
  register: samba_config_st_pre
  changed_when: true
  notify: check smb.conf
  tags:
    - samba
    - service

- name: configure nmbd service
  service:
    arguments: "{{ nmbd_service_arguments | default(omit) }}"
    enabled: "{{ nmbd_service_enabled | default(omit) | bool }}"
    name: "{{ nmbd_service_name }}"
    pattern: "{{ nmbd_service_pattern | default(omit) }}"
    runlevel: "{{ nmbd_service_runlevel | default(omit) }}"
    sleep: "{{ nmbd_service_sleep | default(omit) }}"
    enabled: "{{ nmbd_service_enabled | default(omit) }}"
  when: nmbd_service_enabled is defined
  tags:
    - samba
    - service

- name: configure smbd service
  service:
    arguments: "{{ smbd_service_arguments | default(omit) }}"
    enabled: "{{ smbd_service_enabled | default(omit) | bool }}"
    name: "{{ smbd_service_name }}"
    pattern: "{{ smbd_service_pattern | default(omit) }}"
    runlevel: "{{ smbd_service_runlevel | default(omit) }}"
    sleep: "{{ smbd_service_sleep | default(omit) }}"
    enabled: "{{ smbd_service_enabled | default(omit) }}"
  when: smbd_service_enabled is defined
  tags:
    - samba
    - service
