---
- name: configure nmbd service
  service:
    arguments: "{{ nmbd_service_arguments | default(omit) }}"
    enabled: "{{ nmbd_service_enabled | default(omit) | bool }}"
    name: "{{ nmbd_service_name }}"
    pattern: "{{ nmbd_service_pattern | default(omit) }}"
    runlevel: "{{ nmbd_service_runlevel | default(omit) }}"
    sleep: "{{ nmbd_service_sleep | default(omit) }}"
    state: "{{ nmbd_service_state | default(omit) }}"
  tags:
    - samba
    - service

- name: configure smbd service
  service:
    arguments: "{{ smbd_service_arguments | default(omit) }}"
    enabled: "{{ smbd_service_enabled | default(omit) | bool }}"
    name: "{{ smbd_service_name }}"
    pattern: "{{ smbd_service_pattern | default(omit) }}"
    runlevel: "{{ smbd_service_runlevel | default(omit) }}"
    sleep: "{{ smbd_service_sleep | default(omit) }}"
    state: "{{ smbd_service_state | default(omit) }}"
  tags:
    - samba
    - service
