---
# handlers file for samba
- name: get post-run stat of smb.conf
  stat:
    follow: "{{ samba_config_follow | default(omit) }}"
    get_checksum: yes
    path: "{{ samba_config_dest }}"
  register: samba_config_st_post
  changed_when: true
  notify:
    - compare smb.conf checksums
  tags:
    - samba
    - service

- name: compare smb.conf checksums
  debug:
    msg: Triggering service restarts if smb.conf has changed
  changed_when: samba_config_st_pre.stat.checksum != samba_config_st_post.stat.checksum
  notify:
    - restart nmbd service
    - restart smbd service
  tags:
    - samba
    - service

- name: restart samba services
  debug:
    msg: restarting samba services
  changed_when: true
  notify:
    - restart nmbd service
    - restart smbd service
  tags:
    - samba
    - service

- name: restart nmbd service
  service:
    arguments: "{{ nmbd_service_arguments | default(omit) }}"
    name: "{{ nmbd_service_name }}"
    pattern: "{{ nmbd_service_pattern | default(omit) }}"
    runlevel: "{{ nmbd_service_runlevel | default(omit) }}"
    sleep: "{{ nmbd_service_sleep | default(omit) }}"
    state: restarted
  when: samba_service_enabled | default('no') | bool
  tags:
    - samba
    - service

- name: restart smbd service
  service:
    arguments: "{{ smbd_service_arguments | default(omit) }}"
    name: "{{ smbd_service_name }}"
    pattern: "{{ smbd_service_pattern | default(omit) }}"
    runlevel: "{{ smbd_service_runlevel | default(omit) }}"
    sleep: "{{ smbd_service_sleep | default(omit) }}"
    state: restarted
  when: samba_service_enabled | default('no') | bool
  tags:
    - samba
    - service
